# ----- Dala Stellar Anchor <dala.org> -----

ACCOUNTS=["GAI5SVKCB5QTCK7NI2BM5V7GKSFIK3XCZEDAXP3QCANWNJCM2C3TOOBU", "GDM76YI22CITQRZ4O7D7OHEIGYBPUEKDWM6BZ3VGU6JHCJUNNSWOERVZ"]

[DOCUMENTATION]
ORG_NAME="Dala Cayman Ltd"
ORG_DBA="Dala"
ORG_URL="https://dala.org"
ORG_LOGO="https://dala.org/dala-logo-150x150.png"
ORG_DESCRIPTION="A decentralized financial system for emerging markets."
ORG_PHYSICAL_ADDRESS="Plantation House, P.O. Box 1968, 196 Raleigh Quay, Grand Cayman KY1-1104, Cayman Islands"
ORG_KEYBASE="getdala"
ORG_TWITTER="DalaFoundation"
ORG_GITHUB="GetDala"
ORG_OFFICIAL_EMAIL="info@dala.org"

[[PRINCIPALS]]
name="Tricia Martinez"
email="tricia@dala.org"
twitter="TriciaTita"

[[PRINCIPALS]]
name="Samer Saab"
email="samer@dala.org"
twitter="Samer_Saab"

[[PRINCIPALS]]
name="Ross McEwan"
email="ross@dala.org"
twitter="ross_mcewan"
keybase="rossmcewan"
github="rossmcewan"

[[PRINCIPALS]]
name="Llew Claasen"
email="llew@dala.org"
twitter="LlewClaasen"

[[CURRENCIES]]
code="DALA"
issuer="GAI5SVKCB5QTCK7NI2BM5V7GKSFIK3XCZEDAXP3QCANWNJCM2C3TOOBU"
display_decimals=7
name="Dala"
desc="The Dala Token"
image="https://dala.org/dala-logo-150x150.png"

# ----- Haere ra! -----